name: Publish Package

on:
  release:
    types: [published] # Trigger when a release is published on GitHub

permissions:
  contents: read # Need read to checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for softprops/action-gh-release
      id-token: write # Needed for npm provenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest checkout action

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile # Use frozen lockfile for reproducibility

      - name: Build project
        run: bun run build

      - name: Build native binaries
        run: bun run build:native

      - name: Publish to NPM
        # Assumes NODE_AUTH_TOKEN is set in secrets for npm publish
        run: npm publish --provenance --access public # Add provenance and ensure public access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2 # Use updated action version
        with:
          # Get tag name from the release event that triggered the workflow
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ./dist-bin/rules-linux
            ./dist-bin/rules-macos
            ./dist-bin/rules-win.exe
        env:
          # GITHUB_TOKEN is automatically available
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 