name: Release Please

on:
  workflow_dispatch: # Allow manual triggering

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node # Explicitly state release-type
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json # Use a manifest for future flexibility if needed
          token: ${{ secrets.GITHUB_TOKEN }}

# The publish job below this line should be removed as it's handled by publish.yml 